"""empty message

Revision ID: 8910f723e71b
Revises: 
Create Date: 2019-12-30 12:30:09.805809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910f723e71b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('batch_name')
    )
    op.create_table('test_type',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_type_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('test_type_name')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo_item', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_name', sa.String(length=250), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('section_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section')
    op.drop_table('todo')
    op.drop_table('test_type')
    op.drop_table('batch')
    # ### end Alembic commands ###
